[package]
name = "ports-interface"
version = "0.1.0"
edition = "2021"
description = "Defines the interface of the various adapters."

[dependencies]
sbor = { workspace = true, default-features = true }
scrypto = { workspace = true, default-features = true }
radix-transactions = { workspace = true, default-features = true, optional = true }
radix-common = { workspace = true, default-features = true }
radix-common-derive = { workspace = true, default-features = true }
radix-engine-interface = { workspace = true, default-features = true }

common = { path = "../common" }
scrypto-interface = { path = "../scrypto-interface" }

[features]
default = [
    "trait",
    "scrypto-stubs",
    "scrypto-test-stubs",
    "manifest-builder-stubs",
]
trait = []
scrypto-stubs = []
scrypto-test-stubs = []
manifest-builder-stubs = ["dep:radix-transactions"]

[lib]
crate-type = ["cdylib", "lib"]
