[package]
name = "decimal"
version = "1.0.0-rc1"
edition = "2021"

[dependencies]
scrypto = { path = "../../../../scrypto", features = ["outsource-decimal-arithmetic-to-engine"] }

[dev-dependencies]
radix-engine = { path = "../../../../radix-engine" }

[lib]
doctest = false
crate-type = ["cdylib", "lib"]
