[package]
name = "ociswap-v1-adapter-v1"
version = "0.1.0"
edition = "2021"
description = "Defines the adapter for Ociswap v1 - this is effectively deprecated since we won't be supporting Ociswap v1."

[dependencies]
sbor = { workspace = true, default-features = true }
scrypto = { workspace = true, default-features = true }
radix-common = { workspace = true, default-features = true }
radix-engine-interface = { workspace = true, default-features = true }
radix-transactions = { workspace = true, default-features = true, optional = true }

scrypto-interface = { path = "../../libraries/scrypto-interface" }
ports-interface = { path = "../../libraries/ports-interface" }
common = { path = "../../libraries/common" }

[features]
default = []
test = []

manifest-builder-stubs = ["dep:radix-transactions"]

[lib]
crate-type = ["cdylib", "lib"]
